# Generated by Django 3.0.6 on 2020-05-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='1', upload_to='static/img'),
            preserve_default=False,
        ),
    ]
